# Generated by Django 5.0.6 on 2024-07-22 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TvProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除标志')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='节目名称')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tv/program/logos', verbose_name='节目Logo')),
                ('last_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='上次更新时间')),
            ],
            options={
                'verbose_name': '电视节目',
                'verbose_name_plural': '电视节目',
                'db_table': 'tv_program',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除标志')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='视频名称')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='时间')),
                ('related_link', models.URLField(blank=True, null=True, verbose_name='相关链接')),
                ('origin_link', models.URLField(blank=True, null=True, verbose_name='原始视频链接')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='tv/video/cover', verbose_name='视频封面')),
                ('program', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='television.tvprogram')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'db_table': 'tv_video',
            },
        ),
    ]
