# Generated by Django 5.0.6 on 2024-07-22 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('television', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='program',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='television.tvprogram', verbose_name='电视节目'),
        ),
    ]
