# Generated by Django 5.0.6 on 2024-07-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('television', '0002_alter_video_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='tv/video/raw-videos', verbose_name='视频文件'),
        ),
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='tv/video/covers', verbose_name='视频封面'),
        ),
    ]
