# Generated by Django 5.0.6 on 2024-07-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('television', '0003_video_video_alter_video_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvprogram',
            name='last_updated_at',
        ),
        migrations.AddField(
            model_name='tvprogram',
            name='first_detected_update_time',
            field=models.DateTimeField(blank=True, help_text='节目在官网或订阅源网站上首次检测到更新的时间。', null=True, verbose_name='节目更新时间'),
        ),
        migrations.AddField(
            model_name='tvprogram',
            name='last_synced_time',
            field=models.DateTimeField(blank=True, help_text='爬虫程序上一次去视频发布源检索节目的时间。', null=True, verbose_name='上次同步时间'),
        ),
        migrations.AddField(
            model_name='tvprogram',
            name='local_update_time',
            field=models.DateTimeField(blank=True, help_text='节目最新的视频文件下载到本地的时间。', null=True, verbose_name='本地更新时间'),
        ),
        migrations.AddField(
            model_name='tvprogram',
            name='source_url',
            field=models.URLField(blank=True, help_text='节目的数据来源网址，以便于爬虫程序获取更新。', null=True, verbose_name='节目来源URL'),
        ),
        migrations.AddField(
            model_name='tvprogram',
            name='status',
            field=models.CharField(choices=[('updated', '已更新'), ('pending_update', '待更新'), ('downloading', '下载中'), ('failed', '下载失败')], default='pending_update', help_text='用于记录节目的当前状态，便于管理和调度。', max_length=20, verbose_name='状态'),
        ),
    ]
