# Generated by Django 5.0.6 on 2024-07-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('television', '0006_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvprogram',
            name='status',
            field=models.CharField(choices=[('updated', '已更新'), ('pending_update', '待更新'), ('scraping', '采集中'), ('downloading', '下载中'), ('failed', '下载失败')], default='pending_update', help_text='用于记录节目的当前状态，便于管理和调度。', max_length=20, verbose_name='状态'),
        ),
    ]
